use_frameworks!

platform :ios, '11.0'

target 'UalaNavigationEngine_Example' do
  pod 'UalaNavigationEngine', :path => '../'

  target 'UalaNavigationEngine_Tests' do
    inherit! :search_paths
  end
end
